version: '3.4'

services:
  waambokt-dev:
    build: .
    restart: unless-stopped
    container_name: waambokt-dev
    env_file:
      - .env
    environment:
      - ENV=DEV
    networks:
      - waambokt-dev-network

networks:
  waambokt-dev-network:
    driver: bridge